version: 0.2

phases:
    install:
        runtime-versions:
            java: openjdk8
    pre_build:
        commands:
            - echo "Pre_build"
    build:
        commands:
            - echo "Build"
            - mvn clean install
    post_build:
        commands:
            - echo "Post_build"
artifacts:
    files:
        target/springtest.jar
